from lib.Config import Config
import logging
import json

logger = logging.getLogger(__name__)

class DFGTransformer:
    def __init__(self):
        self.config = self._load_config()


    def _load_config(self):
        """
        Initializes and returns the configuration instance.
        """
        config_instance = Config()
        config_instance.initialize()
        return config_instance.get()
    

    def build_activity_mapping_from_dfg(self, dfg_path, mapping_path):
        """
        Builds an activity mapping (ACT_0, ACT_1, ...) from the original
        PM4Py DFG file, using the activity list at the top of the file.

        Input (dfg_path): PM4Py DFG format
            - First line: number of activities
            - Next N lines: activity labels (one per line)
            - The rest of the file (starts, ends, transitions) is ignored here.

        Output (mapping_path):
            One line per activity:
            ACT_0 = activity_name
            ACT_1 = activity_name
            ...
        """
        activities = self._create_activities_list(dfg_path)

        # Generate mapping ACT_x = activity
        with open(mapping_path, 'w', encoding='utf-8') as out:
            for idx, name in enumerate(activities):
                act_id = f"ACT_{idx}"
                out.write(f"{act_id} = {name}\n")

        logger.debug(
            f"Activity mapping (from PM4Py) written to {mapping_path} "
            f"({len(activities)} activities)"
    )

        
    def transform_dfg(self, dfg_path, output_path):
        """
        Transforms the original DFG to enhance LLM processing.
        """
        transformed_dfg_lines = []

        # 1) Get activities (index -> label)
        activities = self._create_activities_list(dfg_path)
        logger.debug(f"Loaded {len(activities)} activities")
        logger.debug(f"Activities: {activities}")

        with open(dfg_path, 'r', encoding='utf-8') as f:
            num_activities = int(f.readline().strip())
            for _ in range(num_activities):
                f.readline()  # skip activity lines (already in activities)

            # 2) Start activities
            transformed_dfg_lines.append("### START_ACTIVITIES")
            num_start_activities = int(f.readline().strip())
            for _ in range(num_start_activities):
                line = f.readline().rstrip() # e.g. "28x21"
                activity_id_str, freq_str = line.split("x")
                activity_idx = int(activity_id_str)
                activity_name = activities[activity_idx]
                transformed_dfg_lines.append(f"{activity_name} x {freq_str}")

            # 3) End activities
            transformed_dfg_lines.append("### END_ACTIVITIES")
            num_end_activities = int(f.readline().strip())
            for _ in range(num_end_activities):
                line = f.readline().rstrip()          # e.g. "28x9"
                activity_id_str, freq_str = line.split("x")
                activity_idx = int(activity_id_str)
                activity_name = activities[activity_idx]
                transformed_dfg_lines.append(f"{activity_name} x {freq_str}")

            # 4) Transitions
            transformed_dfg_lines.append("### TRANSITIONS")
            for line in f:
                line = line.strip()
                if not line:
                    continue
                # format: "28>41x2154"
                src_dest, freq_str = line.split("x")
                src_str, dest_str = src_dest.split(">")
                src_idx = int(src_str)
                dest_idx = int(dest_str)
                src_name = activities[src_idx]
                dest_name = activities[dest_idx]
                transformed_dfg_lines.append(f"{src_name} -> {dest_name} x {freq_str}")

            # 5) Write transformed file
            with open(output_path, 'w', encoding='utf-8') as out:
                out.write("\n".join(transformed_dfg_lines))

            logger.info(f"Transformed DFG written to {output_path}")


    def apply_activity_mapping_to_named(self, named_dfg_path, mapping_path, act_dfg_path):
        """
        Reads a custom named DFG (with activity names) and a mapping file generated by
        build_activity_mapping_from_named(), and produces a DFG where all
        activity names are replaced by their corresponding ACT_x IDs.

        Input:
            named_dfg_path: custom DFG with activity names
            mapping_path: file with lines "ACT_k = activity_name"
        Output:
            act_dfg_path: same structure as named_dfg_path but using ACT_x IDs
        """
        # 1) Load mapping: activity_name -> ACT_x
        name_to_id = {}
        with open(mapping_path, 'r', encoding='utf-8') as f_map:
            for raw_line in f_map:
                line = raw_line.strip()
                if not line or "=" not in line:
                    continue
                act_id_part, name_part = line.split("=", 1)
                act_id = act_id_part.strip()        # e.g. "ACT_0"
                activity_name = name_part.strip()   # e.g. "\core\event\course_viewed"
                name_to_id[activity_name] = act_id

        act_dfg_lines = []
        section = None

        with open(named_dfg_path, 'r', encoding='utf-8') as f:
            for raw_line in f:
                original_line = raw_line.rstrip("\n")
                line = original_line.strip()

                # Detect section headers
                if line.startswith("###"):
                    upper = line.upper()
                    if "START_ACTIVITIES" in upper:
                        section = "start"
                    elif "END_ACTIVITIES" in upper:
                        section = "end"
                    elif "TRANSITIONS" in upper:
                        section = "trans"
                    else:
                        section = None
                    # Copy section header as is
                    act_dfg_lines.append(line)
                    continue

                # START / END: "activity_name x freq"
                if section in ("start", "end"):
                    if " x " in line:
                        name_part, freq_part = line.rsplit(" x ", 1)
                    else:
                        name_part, freq_part = line.rsplit("x", 1)
                    activity_name = name_part.strip()
                    freq = freq_part.strip()

                    act_id = name_to_id.get(activity_name)
                    if act_id is None:
                        # In case there is a name not found in the mapping
                        logger.warning(f"Activity '{activity_name}' not found in mapping; "
                                    f"keeping original name.")
                        act_id = activity_name

                    act_dfg_lines.append(f"{act_id} x {freq}")

                # TRANSITIONS: "src_name -> dest_name x freq"
                elif section == "trans":
                    if " x " in line:
                        left, freq_part = line.rsplit(" x ", 1)
                    else:
                        left, freq_part = line.rsplit("x", 1)
                    freq = freq_part.strip()

                    src_part, dest_part = left.split("->")
                    src_name = src_part.strip()
                    dest_name = dest_part.strip()

                    src_id = name_to_id.get(src_name)
                    dest_id = name_to_id.get(dest_name)

                    if src_id is None:
                        logger.warning(f"Source activity '{src_name}' not found in mapping; "
                                    f"keeping original name.")
                        src_id = src_name
                    if dest_id is None:
                        logger.warning(f"Target activity '{dest_name}' not found in mapping; "
                                    f"keeping original name.")
                        dest_id = dest_name

                    act_dfg_lines.append(f"{src_id} -> {dest_id} x {freq}")

        with open(act_dfg_path, 'w', encoding='utf-8') as out:
            out.write("\n".join(act_dfg_lines))

        logger.info(f"ACT-ID DFG written to {act_dfg_path}")


    def act_ids_to_named_dfg(self, act_dfg_path, mapping_path, named_output_path):
        """
        Converts a simplified DFG that uses ACT_x IDs back into a named DFG
        (with full activity names), keeping the same custom format:

        ### START_ACTIVITIES
        activity_name x freq
        ### END_ACTIVITIES
        activity_name x freq
        ### TRANSITIONS
        activity_name_src -> activity_name_dst x freq


        Inputs:
        - act_dfg_path: DFG simplified by the LLM (using ACT_x IDs)
        - mapping_path: file with lines "ACT_k = activity_name"
        - named_output_path: output file with full activity names
        """
        
        # 1) Load mapping: ACT_x -> activity_name
        id_to_name = {}
        with open(mapping_path, 'r', encoding='utf-8') as f_map:
            for raw_line in f_map:
                line = raw_line.strip()
                if not line or "=" not in line:
                    continue
                act_id_part, name_part = line.split("=", 1)
                act_id = act_id_part.strip()       # e.g. "ACT_0"
                activity_name = name_part.strip()  # e.g. "\core\event\course_viewed"
                id_to_name[act_id] = activity_name
        
        named_lines = []
        section = None

        # 2) Read the DFG with ACT_x and replace with names
        with open(act_dfg_path, 'r', encoding='utf-8') as f:
            for raw_line in f:
                original_line = raw_line.rstrip("\n")
                line = original_line.strip()

                # Detect sections
                if line.startswith("###"):
                    upper = line.upper()
                    if "START" in upper:
                        section = "start"
                    elif "END" in upper:
                        section = "end"
                    elif "TRANSITIONS" in upper:
                        section = "trans"
                    else:
                        section = None
                    # copy the header as is
                    named_lines.append(line)
                    continue

                if not line:
                    continue

                # START / END: "ACT_x x freq"
                if section in ("start", "end"):
                    if " x " in line:
                        id_part, freq_part = line.rsplit(" x ", 1)
                    else:
                        id_part, freq_part = line.rsplit("x", 1)
                    act_id = id_part.strip()
                    freq = freq_part.strip()

                    activity_name = id_to_name.get(act_id, act_id)
                    named_lines.append(f"{activity_name} x {freq}")

                # TRANSITIONS: "ACT_x -> ACT_y x freq"
                elif section == "trans":
                    if " x " in line:
                        left, freq_part = line.rsplit(" x ", 1)
                    else:
                        left, freq_part = line.rsplit("x", 1)
                    freq = freq_part.strip()

                    src_part, dest_part = left.split("->")
                    src_id = src_part.strip()
                    dest_id = dest_part.strip()

                    src_name = id_to_name.get(src_id, src_id)
                    dest_name = id_to_name.get(dest_id, dest_id)

                    named_lines.append(f"{src_name} -> {dest_name} x {freq}")

                else:
                    continue

        # 3) Save result
        with open(named_output_path, 'w', encoding='utf-8') as out:
            out.write("\n".join(named_lines))

        logger.info(f"Named DFG (from ACT IDs) written to {named_output_path}")



    def restore_dfg(self, custom_dfg_path, output_path):
        """
        Transforms a custom DFG back into PM4Py DFG format (with integer indices).
        """

        activities_index = {}   # name -> index
        activities_list = []    # index -> name

        start_entries = []      # (activity_name, freq)
        end_entries = []        # (activity_name, freq)
        transitions = []        # (src_name, dst_name, freq)

        def get_or_create_index(activity_name: str) -> int:
            """Assign an index to the activity if it does not exist yet."""
            if activity_name not in activities_index:
                idx = len(activities_list)
                activities_index[activity_name] = idx
                activities_list.append(activity_name)
            return activities_index[activity_name]

        # 1) Parse custom DFG
        section = None
        with open(custom_dfg_path, 'r', encoding='utf-8') as f:
            for raw_line in f:
                line = raw_line.strip()
                if not line:
                    continue

                # Detect sections
                if line.startswith("###"):
                    upper = line.upper()
                    if "START" in upper:
                        section = "start"
                    elif "END" in upper:
                        section = "end"
                    elif "TRANSITIONS" in upper:
                        section = "trans"
                    else:
                        section = None
                    continue

                # START_ACTIVITIES: "<name> x <freq>"
                if section == "start":
                    if " x " in line:
                        name_part, freq_part = line.rsplit(" x ", 1)
                    else:
                        name_part, freq_part = line.rsplit("x", 1)

                    activity_name = name_part.strip()
                    freq = int(freq_part.strip())

                    start_entries.append((activity_name, freq))
                    get_or_create_index(activity_name)

                # END_ACTIVITIES: "<name> x <freq>"
                elif section == "end":
                    if " x " in line:
                        name_part, freq_part = line.rsplit(" x ", 1)
                    else:
                        name_part, freq_part = line.rsplit("x", 1)

                    activity_name = name_part.strip()
                    freq = int(freq_part.strip())

                    end_entries.append((activity_name, freq))
                    get_or_create_index(activity_name)

                # TRANSITIONS: "<src> -> <dest> x <freq>"
                elif section == "trans":
                    if " x " in line:
                        left, freq_part = line.rsplit(" x ", 1)
                    else:
                        left, freq_part = line.rsplit("x", 1)
                    freq = int(freq_part.strip())

                    src_part, dest_part = left.split("->")
                    src_name = src_part.strip()
                    dest_name = dest_part.strip()

                    transitions.append((src_name, dest_name, freq))
                    get_or_create_index(src_name)
                    get_or_create_index(dest_name)

        # 2) Write in PM4Py format
        with open(output_path, 'w', encoding='utf-8') as out:
            # Number of activities
            out.write(f"{len(activities_list)}\n")
            # List of activities (ya con nombres definitivos)
            for name in activities_list:
                out.write(f"{name}\n")

            # Start activities
            out.write(f"{len(start_entries)}\n")
            for name, freq in start_entries:
                idx = activities_index[name]
                out.write(f"{idx}x{freq}\n")

            # End activities
            out.write(f"{len(end_entries)}\n")
            for name, freq in end_entries:
                idx = activities_index[name]
                out.write(f"{idx}x{freq}\n")

            # Transitions
            for src_name, dest_name, freq in transitions:
                src_idx = activities_index[src_name]
                dest_idx = activities_index[dest_name]
                out.write(f"{src_idx}>{dest_idx}x{freq}\n")

        logger.info(f"Restored PM4Py DFG written to {output_path}")



    def dfg_pm4py_to_json(self, dfg_path: str, json_output_path: str) -> None:
        """
        Converts a PM4Py DFG file into a JSON representation using activity *names*.

        Output JSON structure:
        {
        "start_activities": [
            { "activity": "<name>", "freq": <int> },
            ...
        ],
        "end_activities": [
            { "activity": "<name>", "freq": <int> },
            ...
        ],
        "transitions": [
            { "src": "<name>", "tgt": "<name>", "freq": <int> },
            ...
        ]
        }
        """
        with open(dfg_path, 'r', encoding='utf-8') as f:
            # 1) Activities
            num_activities = int(f.readline().strip())
            activities = []
            for _ in range(num_activities):
                label = f.readline().rstrip("\n")
                activities.append(label)

            # 2) Start activities
            start_activities = []
            num_start = int(f.readline().strip())
            for _ in range(num_start):
                line = f.readline().strip()   # e.g. "28x21"
                if not line:
                    continue
                idx_str, freq_str = line.split("x")
                idx = int(idx_str)
                freq = int(freq_str)
                start_activities.append({
                    "activity": activities[idx],
                    "freq": freq
                })

            # 3) End activities
            end_activities = []
            num_end = int(f.readline().strip())
            for _ in range(num_end):
                line = f.readline().strip()   # e.g. "28x9"
                if not line:
                    continue
                idx_str, freq_str = line.split("x")
                idx = int(idx_str)
                freq = int(freq_str)
                end_activities.append({
                    "activity": activities[idx],
                    "freq": freq
                })

            # 4) Transitions
            transitions = []
            for line in f:
                line = line.strip()
                if not line:
                    continue
                # format: "28>41x2154"
                src_dest, freq_str = line.split("x")
                src_str, dst_str = src_dest.split(">")
                src_idx = int(src_str)
                dst_idx = int(dst_str)
                freq = int(freq_str)
                transitions.append({
                    "src": activities[src_idx],
                    "tgt": activities[dst_idx],
                    "freq": freq
                })

        dfg_json = {
            "start_activities": start_activities,
            "end_activities": end_activities,
            "transitions": transitions
        }

        with open(json_output_path, 'w', encoding='utf-8') as out:
            json.dump(dfg_json, out, ensure_ascii=False, indent=2)

        logger.info(f"PM4Py DFG converted to JSON and saved at {json_output_path}")

    

    def dfg_json_replace_activities_with_generics(self, 
                                            input_json_path: str,
                                            output_json_path: str,
                                            mapping_output_path: str,
                                            prefix: str = "ACT_") -> None:
        """
        Reads a DFG JSON (with activity names) and produces:
        - a new JSON where activities are replaced by generic IDs (ACT_0, ACT_1, ...)
        - a mapping JSON file: { "ACT_0": "<original_name>", ... }

        Input JSON (simplified):
        {
        "start_activities": [ { "activity": "<name>", "freq": int }, ... ],
        "end_activities":   [ { "activity": "<name>", "freq": int }, ... ],
        "transitions":      [ { "src": "<name>", "tgt": "<name>", "freq": int }, ... ]
        }

        Output JSON:
        same structure, but "activity", "src" and "tgt" use ACT_x IDs instead of names.
        """
        with open(input_json_path, 'r', encoding='utf-8') as f:
            data = json.load(f)

        # 1) Recolectar todos los nombres de actividad
        activity_names = set()

        for entry in data.get("start_activities", []):
            activity_names.add(entry["activity"])

        for entry in data.get("end_activities", []):
            activity_names.add(entry["activity"])

        for t in data.get("transitions", []):
            activity_names.add(t["src"])
            activity_names.add(t["tgt"])

        # 2) Crear mapping determinista nombre -> ACT_x (ordenado por nombre)
        sorted_names = sorted(activity_names)
        name_to_id = {}
        id_to_name = {}

        for idx, name in enumerate(sorted_names):
            act_id = f"{prefix}{idx}"
            name_to_id[name] = act_id
            id_to_name[act_id] = name

        # 3) Construir nuevo JSON con IDs
        new_start = []
        for entry in data.get("start_activities", []):
            new_start.append({
                "activity": name_to_id[entry["activity"]],
                "freq": entry["freq"]
            })

        new_end = []
        for entry in data.get("end_activities", []):
            new_end.append({
                "activity": name_to_id[entry["activity"]],
                "freq": entry["freq"]
            })

        new_transitions = []
        for t in data.get("transitions", []):
            new_transitions.append({
                "src": name_to_id[t["src"]],
                "tgt": name_to_id[t["tgt"]],
                "freq": t["freq"]
            })

        new_data = {
            "start_activities": new_start,
            "end_activities": new_end,
            "transitions": new_transitions
        }

        # 4) Guardar JSON con IDs
        with open(output_json_path, 'w', encoding='utf-8') as out:
            json.dump(new_data, out, ensure_ascii=False, indent=2)

        # 5) Guardar mapping ACT_x -> nombre original
        with open(mapping_output_path, 'w', encoding='utf-8') as map_out:
            json.dump(id_to_name, map_out, ensure_ascii=False, indent=2)



    def dfg_json_restore_activity_names(self,
                                        act_json_path: str,
                                        mapping_path: str,
                                        output_json_path: str) -> None:
        """
        Restores original activity names in a JSON DFG that uses IDs (ACT_0, ACT_1, ...),
        using a JSON mapping file of the form:
        { "ACT_0": "<original_name>", "ACT_1": "<original_name>", ... }

        Input JSON (act_json_path):
        {
            "start_activities": [ { "activity": "ACT_0", "freq": int }, ... ],
            "end_activities":   [ { "activity": "ACT_3", "freq": int }, ... ],
            "transitions":      [ { "src": "ACT_0", "tgt": "ACT_1", "freq": int }, ... ]
        }

        Output JSON (output_json_path):
        Same structure, but with original names instead of ACT_x.
        """

        # 1) Load JSON DFG with ACT_x
        with open(act_json_path, 'r', encoding='utf-8') as f:
            dfg_data = json.load(f)

        # 2) Load mapping ACT_x -> original name
        with open(mapping_path, 'r', encoding='utf-8') as f_map:
            id_to_name = json.load(f_map)

        # Helper to map an ID or leave it as is if not in the mapping
        def map_id(act_id: str) -> str:
            return id_to_name.get(act_id, act_id)

        # 3) Restore names in start_activities
        restored_start = []
        for entry in dfg_data.get("start_activities", []):
            restored_start.append({
                "activity": map_id(entry["activity"]),
                "freq": int(entry["freq"])
            })

        # 4) Restore names in end_activities
        restored_end = []
        for entry in dfg_data.get("end_activities", []):
            restored_end.append({
                "activity": map_id(entry["activity"]),
                "freq": int(entry["freq"])
            })

        # 5) Restore names in transitions
        restored_transitions = []
        for t in dfg_data.get("transitions", []):
            restored_transitions.append({
                "src":  map_id(t["src"]),
                "tgt":  map_id(t["tgt"]),
                "freq": int(t["freq"])
            })

        restored_data = {
            "start_activities": restored_start,
            "end_activities": restored_end,
            "transitions": restored_transitions
        }

        # 6) Save restored JSON
        with open(output_json_path, 'w', encoding='utf-8') as out:
            json.dump(restored_data, out, ensure_ascii=False, indent=2)


    def dfg_named_json_to_pm4py(self,
                                named_json_path: str,
                                dfg_output_path: str) -> None:
        """
        Converts a DFG in JSON format (with activity names) to the
        PM4Py DFG format.

        Input (named_json_path):
        {
            "start_activities": [
            { "activity": "<name>", "freq": int }, ...
            ],
            "end_activities": [
            { "activity": "<name>", "freq": int }, ...
            ],
            "transitions": [
            { "src": "<name>", "tgt": "<name>", "freq": int }, ...
            ]
        }

        Output (dfg_output_path): text file in pm4py format:
        <num_activities>
        <activity_0>
        <activity_1>
        ...
        <num_start_activities>
        <idx>x<freq>
        ...
        <num_end_activities>
        <idx>x<freq>
        ...
        <src_idx>><tgt_idx>x<freq>
        ...
        """

        # 1) Load JSON
        with open(named_json_path, 'r', encoding='utf-8') as f:
            data = json.load(f)

        start_activities = data.get("start_activities", [])
        end_activities = data.get("end_activities", [])
        transitions = data.get("transitions", [])

        # 2) Collect all distinct activities
        activity_names = set()

        for entry in start_activities:
            activity_names.add(entry["activity"])

        for entry in end_activities:
            activity_names.add(entry["activity"])

        for t in transitions:
            activity_names.add(t["src"])
            activity_names.add(t["tgt"])

        # 3) Create sorted list and name -> index mapping
        #    (sorting alphabetically gives reproducibility)
        activities_list = sorted(activity_names)
        activity_to_idx = {name: idx for idx, name in enumerate(activities_list)}

        # 4) Write the file in pm4py format
        with open(dfg_output_path, 'w', encoding='utf-8') as out:
            # Number of activities
            out.write(f"{len(activities_list)}\n")
            # List of activities
            for name in activities_list:
                out.write(f"{name}\n")

            # Start activities
            out.write(f"{len(start_activities)}\n")
            for entry in start_activities:
                name = entry["activity"]
                freq = int(entry["freq"])
                idx = activity_to_idx[name]
                out.write(f"{idx}x{freq}\n")

            # End activities
            out.write(f"{len(end_activities)}\n")
            for entry in end_activities:
                name = entry["activity"]
                freq = int(entry["freq"])
                idx = activity_to_idx[name]
                out.write(f"{idx}x{freq}\n")

            # Transitions
            for t in transitions:
                src_name = t["src"]
                tgt_name = t["tgt"]
                freq = int(t["freq"])
                src_idx = activity_to_idx[src_name]
                tgt_idx = activity_to_idx[tgt_name]
                out.write(f"{src_idx}>{tgt_idx}x{freq}\n")



    
    def _create_activities_list(self, dfg_path):
        """
        Creates and returns the list of activities from a PM4Py DFG file.
        """
        activities = []
        with open(dfg_path, 'r', encoding='utf-8') as f:
            num_activities = int(f.readline().strip())
            for _ in range(num_activities):
                label = f.readline().rstrip("\n")
                activities.append(label)
        return activities
    
