services:
  app:
    image: pm4py-llm-app
    build:
      context: ./app
    container_name: pm4py-llm-app
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app
      - ./dataset:/dataset
      - ./output:/output
    env_file:
      - .env
    user: "${UID}:${GID}"

  orchestrator:
    image: pm4py-llm-orchestrator
    build:
      context: ./orchestrator
    container_name: pm4py-llm-orchestrator
    ports:
      - "8000:8000"
    volumes:
      - ./orchestrator/source:/app/source
    env_file:
      - .env
    depends_on:
      - app
    user: "${UID}:${GID}"

  moodle-data-service:
    image: pm4py-moodle-data-service
    build:
      context: ./moodle-data-service
    container_name: pm4py-moodle-data-service
    ports:
      - "8002:8002"
    volumes:
      - ./moodle-data-service/source:/app/source
      - ./dataset:/dataset
    env_file:
      - .env
    user: "${UID}:${GID}"

  moodle-data-service-worker:
    build:
      context: ./moodle-data-service
    container_name: pm4py-moodle-data-service-worker
    command: ["rq", "worker", "-u", "redis://redis:6379/0", "default"]
    volumes:
      - ./moodle-data-service/source:/app/source
      - ./dataset:/dataset
    env_file:
      - .env
    depends_on:
      - redis
    user: "${UID}:${GID}"

  redis:
    image: redis:7-alpine
    container_name: pm4py-redis
    ports:
      - "6379:6379"

  rq-dashboard:
    image: eoranged/rq-dashboard
    container_name: pm4py-rq-dashboard
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379/0
    ports:
      - "9181:9181"
    depends_on:
      - redis

  mermaid-service:
    image: pm4py-mermaid-service
    build:
      context: ./mermaid-service
    container_name: pm4py-mermaid-service
    ports:
      - "8003:8003"
    volumes:
      - ./mermaid-service/source:/app/source
    env_file:
      - .env
    user: "${UID}:${GID}"

  results-publisher:
    image: pm4py-results-publisher
    build:
      context: ./results-publisher
    container_name: pm4py-results-publisher
    ports:
      - "8004:8004"
    volumes:
      - ./results-publisher/source:/app/source
      - ./output:/output
      - ${LOCAL_PUBLISH_DIRECTORY}:/app/published_results
    env_file:
      - .env
    user: "${UID}:${GID}"

