services:
  app:
    image: pm4py-llm-app
    build:
      context: ./app
    container_name: pm4py-llm-app-container
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app
    env_file:
      - .env

  api:
    image: pm4py-llm-api
    build:
      context: ./api
    container_name: pm4py-llm-api-container
    ports:
      - "8000:8000"
    volumes:
      - ./api/source:/app
    env_file:
      - .env
    depends_on:
      - app
