services:
  pm4py:
    image: pm4py-llm-app
    build:
      context: ./app
    container_name: pm4py-llm-container
    volumes:
      - ./app:/app
    ports:
      - "8001:8001"

  api:
    image: pm4py-llm-api
    build:
      context: ./api
    container_name: api-container
    ports:
      - "8000:8000"
    depends_on:
      - pm4py
    volumes:
      - ./api:/api
