from fastapi import FastAPI, HTTPException, Query, status, Depends
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from dotenv import load_dotenv
from source.models.schemas import *
from config.constants import *
from source.services.pm_analysis_service import PmAnalysisService
from source.services.store_dataset_as_csv import StoreDatasetAsCsvService
from source.services.simplify_dfg_service import SimplifyDFGService
from source.services.build_mind_map_service import MindMapBuilderService
from source.services.get_analysis_service import GetAnalysisService
import os
import logging
import sys



load_dotenv()
API_TOKEN = os.getenv("API_TOKEN")
LOG_LEVEL = os.getenv("LOG_LEVEL", "DEBUG").upper()
output_dir = "/output"
dataset_dir = "/dataset"

if not API_TOKEN:
    raise RuntimeError("API_TOKEN is not set in environment variables")

logging.basicConfig(
    level=getattr(logging, LOG_LEVEL, logging.INFO),
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)]
)

logger = logging.getLogger(__name__)


security = HTTPBearer()


def verify_token(credentials: HTTPAuthorizationCredentials = Depends(security)):
    token = credentials.credentials
    if not token or token != API_TOKEN:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or missing token" + API_TOKEN,
        )

app = FastAPI()


@app.post("/pm-analysis", dependencies=[Depends(verify_token)])
def pm_analysis(request: PMAnalysisRequest):
    try:
        service = PmAnalysisService(
            dataset_path=os.path.join(dataset_dir, request.dataset),
            dataset_csv_delimiter=request.dataset_csv_delimiter,
            output_path=request.output_path
        )
        result = service.run_pm_analysis()
        
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/store-dataset", dependencies=[Depends(verify_token)])
def run_script(request: DatasetToStoreRequest):
    try:
        output_path = StoreDatasetAsCsvService.store_json_dataset_as_csv(request.filename, request.data)
        return {"success": True, "file": output_path}
    except ValueError as ve:
        raise HTTPException(status_code=400, detail=str(ve))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post(
    "/simplify-dfg",
    summary="Simplify a Directly-Follows Graph (DFG) using an LLM",
    description=(
        "Simplifies a Directly-Follows Graph (DFG) using a Large Language Model (LLM). "
        "This endpoint requires a **previous process mining analysis** that has generated a DFG file in PM4Py format.\n\n"
        "**Required input:**\n"
        "- `output_path` (str): Path where the DFG file to simplify is located.\n"
        "**Example input:**\n"
        "```json\n"
        "{\n"
        "  \"output_path\": \"my-folder\"\n"
        "}\n"
        "```"
        "\n\n"
        "**Returns:**\n"
        "- `message`: Confirmation of successful simplification.\n"
        "- `output_analysis`: Path to the analysis file generated by the LLM.\n"
        "- `llm_simplified_dfg`: Path to the simplified DFG file generated by the LLM.\n"
        "- `simplified_dfg`: Path to the simplified DFG file in PM4Py format.\n"
        "- `simplified_dfg_images`: Paths to the images representing the simplified DFG, keyed by format.\n\n"
        "**Example response:**\n"
        "```json\n"
        "{\n"
        "  \"message\": \"DFG simplified successfully\",\n"
        "  \"output_analysis\": \"/output/simplified-dfg-analysis.txt\",\n"
        "  \"llm_simplified_dfg\": \"/output/llm-simplified-dfg.txt\",\n"
        "  \"simplified_dfg\": \"/output/simplified-dfg.dfg\",\n"
        "  \"simplified_dfg_images\": {\"svg\": \"/output/simplified-dfg.svg\", \"png\": \"/output/simplified-dfg.png\"}\n"
        "}\n"
        "```"
    ),
    dependencies=[Depends(verify_token)]
)
def simplify_dfg_endpoint(request: SimplifyDFGRequest):
    try:
        
        result = SimplifyDFGService.simplify_dfg(
            output_path=request.output_path
        )

        return {
            "message": "DFG simplified successfully",
            "output_analysis": result["output_analysis"],
            "llm_simplified_dfg": result["llm_simplified_dfg"],
            "simplified_dfg": result["simplified_dfg"],
            "simplified_dfg_images": result["simplified_dfg_images"]
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post(
        "/create-mind-map",
        summary="Create a Mermaid mind map",
        description=(
            "Creates a Mermaid mind map based on the simplified analysis results.\n\n"
            "The format of the image is set in configuration (default is svg).\n\n"
            "**Expected input:**\n"
            "- `analysis_dir` (str): Directory where the analysis results are stored."
            "This directory should contain the simplified DFG analysis file.\n\n"
            "**Example response:**\n"
            "```json\n"
            "{\n"
            "  \"mind_map_file\": \"output/mind_map.mmd\",\n"
            "  \"mind_map_image_file\": \"output/mind_map.svg\"\n"
            "}\n"
            "```"
        ),
        dependencies=[Depends(verify_token)]
)
def create_mind_map(request: CreateMindMapRequest):

    logger.info("Received request to create mind map")

    basepath = os.path.join(output_dir, request.analysis_dir)

    if not os.path.isdir(basepath):
        raise HTTPException(status_code=404, detail="Analysis directory not found")
    
    mind_map_builder_service = MindMapBuilderService()
    result = mind_map_builder_service.build_mind_map(basepath)

    logger.info("Mind map created successfully.")
    logger.debug(f"Mind map file: {result['mind_map_file']}")
    logger.debug(f"Mind map image file: {result['mind_map_image_file']}")


    return result


@app.get(
        "/get-analysis",
        summary="Get analysis results",
        description=(
            "Retrieves the analysis results for a given output directory. Includes simplified DFG information if exists.\n\n"
            "**Example response:**\n"
            "```json\n"
            "{\n"
            "  \"analysis\": \"XXX\",\n"
            "  \"dfg_images\": {\"svg\": \"XXX\", \"png\": \"XXX\"},\n"
            "  \"simplified_dfg_analysis\": \"XXX\",\n"
            "  \"simplified_dfg_images\": {\"svg\": \"XXX\", \"png\": \"XXX\"}\n"
            "}\n"
            "```"
        ),
        dependencies=[Depends(verify_token)]
)
def get_analysis(analysis_dir: str = Query(
                                    alias="analysis_dir",
                                    description="Directory where the analysis results are stored"
                                    )
    ):

    basepath = os.path.join(output_dir, analysis_dir)

    if not os.path.isdir(basepath):
        raise HTTPException(status_code=404, detail="Analysis directory not found")
    
    get_analysis_service = GetAnalysisService()
    result = get_analysis_service.get_analysis_files(basepath)

    dfg_base_paths = result["dfg_images"]
    dfg_analysis_base_path = result["dfg_analysis"]
    simplified_dfg_base_paths = result["simplified_dfg_images"]
    simplified_dfg_analysis_base_path = result["simplified_dfg_analysis"]
    
    try:
        dfg_images = {}
        for image_format, dfg_base_path in dfg_base_paths.items():
            if not os.path.isfile(dfg_base_path):
                raise HTTPException(status_code=404, detail=dfg_base_path + " not found")
            with open(dfg_base_path, "rb") as f:
                dfg_images[image_format] = f.read().hex()
        
        if not os.path.isfile(dfg_analysis_base_path):
            dfg_analysis_text = 'No analysis file found for DFG.'
        else:
            with open(dfg_analysis_base_path, "r") as f:
                dfg_analysis_text = f.read()
        
        result = {
            "analysis": dfg_analysis_text,
            "dfg_images": dfg_images
        }

        if os.path.isfile(simplified_dfg_analysis_base_path):
            with open(simplified_dfg_analysis_base_path, "r") as f:
                simplified_dfg_analysis_text = f.read()
            result["simplified_dfg_analysis"] = simplified_dfg_analysis_text

        simplified_dfg_images = {}
        for image_format, simplified_dfg_base_path in simplified_dfg_base_paths.items():
            if os.path.isfile(simplified_dfg_base_path):
                with open(simplified_dfg_base_path, "rb") as f:
                    simplified_dfg_images[image_format] = f.read().hex()

        if simplified_dfg_images:
            result["simplified_dfg_images"] = simplified_dfg_images

        return result

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    

@app.get(
        "/get-simplified-analysis",
        summary="Get simplified analysis results",
        description=(
            "Retrieves the simplified analysis results for a given output directory.\n\n"
            "**Example response:**\n"
            "```json\n"
            "{\n"
            "  \"simplified_dfg_analysis\": \"XXX\",\n"
            "  \"simplified_dfg_images\": {\"svg\": \"XXX\", \"png\": \"XXX\"}\n"
            "}\n"
            "```"
        ),
        dependencies=[Depends(verify_token)]
)
def get_simplified_analysis(analysis_dir: str = Query(
                                    alias="analysis_dir",
                                    description="Directory where the analysis results are stored"
                                    )
    ):

    basepath = os.path.join(output_dir, analysis_dir)

    if not os.path.isdir(basepath):
        raise HTTPException(status_code=404, detail="Analysis directory not found")
    
    get_analysis_service = GetAnalysisService()
    result = get_analysis_service.get_simplified_analysis_files(basepath)
    simplified_dfg_base_paths = result["simplified_dfg_images"]
    simplified_dfg_analysis_base_path = result["simplified_dfg_analysis"]

    try:
        if not os.path.isfile(simplified_dfg_analysis_base_path):
            raise HTTPException(status_code=404, detail="Simplified DFG files not found")

        if os.path.isfile(simplified_dfg_analysis_base_path):
            with open(simplified_dfg_analysis_base_path, "r") as f:
                simplified_dfg_analysis_text = f.read()

        simplified_dfg_images = {}
        for image_format, simplified_dfg_base_path in simplified_dfg_base_paths.items():
            if not os.path.isfile(simplified_dfg_base_path):
                raise HTTPException(status_code=404, detail=simplified_dfg_base_path + " not found")
            with open(simplified_dfg_base_path, "rb") as f:
                simplified_dfg_images[image_format] = f.read().hex()

        result = {
            "simplified_dfg_analysis": simplified_dfg_analysis_text,
            "simplified_dfg_images": simplified_dfg_images
        }
        
        return result

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    

