from fastapi import FastAPI, HTTPException, Query, status, Depends
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from dotenv import load_dotenv
from source.models.schemas import *
from config.constants import *
from source.services.run_pm_analysis import PmAnalysisService
from source.services.store_dataset_as_csv import StoreDatasetAsCsvService
from source.services.simplify_dfg import SimplifyDFGService
import os
import logging
import sys



load_dotenv()
API_TOKEN = os.getenv("API_TOKEN")
LOG_LEVEL = os.getenv("LOG_LEVEL", "DEBUG").upper()

if not API_TOKEN:
    raise RuntimeError("API_TOKEN is not set in environment variables")

logging.basicConfig(
    level=getattr(logging, LOG_LEVEL, logging.INFO),
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)]
)

logger = logging.getLogger(__name__)


security = HTTPBearer()


def verify_token(credentials: HTTPAuthorizationCredentials = Depends(security)):
    token = credentials.credentials
    if not token or token != API_TOKEN:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or missing token" + API_TOKEN,
        )

app = FastAPI()


@app.post("/pm-analysis", dependencies=[Depends(verify_token)])
def pm_analysis(request: PMAnalysisRequest):
    try:
        service = PmAnalysisService(
            dataset_path=request.dataset_path,
            dataset_csv_delimiter=request.dataset_csv_delimiter,
            output_path=request.output_path
        )
        result = service.run_pm_analysis()
        
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/store-dataset", dependencies=[Depends(verify_token)])
def run_script(request: DatasetToStoreRequest):
    try:
        output_path = StoreDatasetAsCsvService.store_json_dataset_as_csv(request.filename, request.data)
        return {"success": True, "file": output_path}
    except ValueError as ve:
        raise HTTPException(status_code=400, detail=str(ve))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post(
    "/simplify-dfg",
    summary="Simplify a Directly-Follows Graph (DFG) using an LLM",
    description=(
        "Simplifies a Directly-Follows Graph (DFG) using a Large Language Model (LLM). "
        "This endpoint requires a **previous process mining analysis** that has generated a DFG file in PM4Py format.\n\n"
        "**Required input:**\n"
        "- `output_path` (str): Path where the DFG file to simplify is located.\n"
        "\n**Optional input:**\n"
        "- `prompt_context` (Optional[List[str]]): list of prompt context lines to replace the default context. Useful for customizing the LLM behavior.\n\n"
        "**Example input:**\n"
        "```json\n"
        "{\n"
        "  \"output_path\": \"my-folder\",\n"
        "  \"prompt_context\": [\n"
        "    \"### CONTEXT ###\\n\",\n"
        "    \"You are an expert in process mining and data analysis, with a focus on educational data.\",\n"
        "    \"The section ### DFG MODEL ### contains a Directly-Follows Graph (DFG) model extracted from Moodle logs.\",\n"
        "    \"This model represents the activity behavior of students.\",\n"
        "    \"The structure and format of the DFG are described in the section ### DFG FORMAT ### above.\"\n"
        "  ]\n"
        "}\n"
        "```"
        "\n\n"
        "**Returns:**\n"
        "- `message`: Confirmation of successful simplification.\n"
        "- `output_analysis`: Path to the analysis file generated by the LLM.\n"
        "- `llm_simplified_dfg`: Path to the simplified DFG file generated by the LLM.\n"
        "- `simplified_dfg`: Path to the simplified DFG file in PM4Py format.\n"
        "- `simplified_dfg_image`: Path to the image representing the simplified DFG.\n\n"
        "**Example response:**\n"
        "```json\n"
        "{\n"
        "  \"message\": \"DFG simplified successfully\",\n"
        "  \"output_analysis\": \"output/simplified-dfg-analysis.txt\",\n"
        "  \"llm_simplified_dfg\": \"output/llm-simplified-dfg.txt\",\n"
        "  \"simplified_dfg\": \"output/simplified-dfg.dfg\",\n"
        "  \"simplified_dfg_image\": \"output/simplified-dfg.png\"\n"
        "}\n"
        "```"
    ),
    dependencies=[Depends(verify_token)]
)
def simplify_dfg_endpoint(request: SimplifyDFGRequest):
    try:
        
        result = SimplifyDFGService.simplify_dfg(
            output_path=request.output_path,
            prompt_context=request.prompt_context
        )

        return {
            "message": "DFG simplified successfully",
            "output_analysis": result["output_analysis"],
            "llm_simplified_dfg": result["llm_simplified_dfg"],
            "simplified_dfg": result["simplified_dfg"],
            "simplified_dfg_image": result["simplified_dfg_image"]
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get(
        "/get-analysis",
        summary="Get analysis results",
        description=(
            "Retrieves the analysis results for a given output directory. Includes simplified DFG information if exists.\n\n"
            "**Example response:**\n"
            "```json\n"
            "{\n"
            "  \"analysis\": \"XXX\",\n"
            "  \"dfg_image\": \"XXX\",\n"
            "  \"simplified_dfg_analysis\": \"XXX\",\n"
            "  \"simplified_dfg_image\": \"XXX\"\n"
            "}\n"
            "```"
        ),
        dependencies=[Depends(verify_token)]
)
def get_analysis(analysis_dir: str = Query(
                                    alias="analysis_dir",
                                    description="Directory where the analysis results are stored"
                                    )
    ):

    basepath = os.path.join(OUTPUT_PATH, analysis_dir)

    if not os.path.isdir(basepath):
        raise HTTPException(status_code=404, detail="Analysis directory not found")
    
    dfg_base_path = os.path.join(basepath, "dfg.png")
    dfg_analysis_base_path = os.path.join(basepath, "dfg-analysis.txt")
    simplified_dfg_base_path = os.path.join(basepath, "simplified-dfg.png")
    simplified_dfg_analysis_base_path = os.path.join(basepath, "simplified-dfg-analysis.txt")
    
    if not os.path.isfile(dfg_base_path) or not os.path.isfile(dfg_analysis_base_path):
        raise HTTPException(status_code=404, detail=dfg_base_path + " or " + dfg_analysis_base_path + " not found")

    try:
        with open(dfg_analysis_base_path, "r") as f:
            dfgAnalysisText = f.read()
        with open(dfg_base_path, "rb") as f:
            dfgImageBytes = f.read()

        result = {
            "analysis": dfgAnalysisText,
            "dfg_image": dfgImageBytes.hex()
        }

        if os.path.isfile(simplified_dfg_analysis_base_path):
            with open(simplified_dfg_analysis_base_path, "r") as f:
                simplified_dfg_analysis_text = f.read()
            result["simplified_dfg_analysis"] = simplified_dfg_analysis_text

        if os.path.isfile(simplified_dfg_base_path):
            with open(simplified_dfg_base_path, "rb") as f:
                simplified_dfg_image_bytes = f.read()
            result["simplified_dfg_image"] = simplified_dfg_image_bytes.hex()

        return result

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))