from fastapi import FastAPI, HTTPException, Query, status, Depends
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from dotenv import load_dotenv
from source.models.schemas import *
from config.constants import *
from source.services.pm_analysis_service import PmAnalysisService
from source.services.store_dataset_as_csv import StoreDatasetAsCsvService
from source.services.simplify_dfg_service import SimplifyDFGService
from source.services.summarize_simplified_dfg_service import SummarizeSimplifiedDFGService
from source.services.build_mind_map_service import MindMapBuilderService
from source.services.get_analysis_service import GetAnalysisService
import os
import logging
import sys



load_dotenv()
API_TOKEN = os.getenv("API_TOKEN")
LOG_LEVEL = os.getenv("LOG_LEVEL", "DEBUG").upper()
output_dir = "/output"
dataset_dir = "/dataset"

if not API_TOKEN:
    raise RuntimeError("API_TOKEN is not set in environment variables")

logging.basicConfig(
    level=getattr(logging, LOG_LEVEL, logging.INFO),
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)]
)

logger = logging.getLogger(__name__)


security = HTTPBearer()


def verify_token(credentials: HTTPAuthorizationCredentials = Depends(security)):
    token = credentials.credentials
    if not token or token != API_TOKEN:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or missing token",
        )

app = FastAPI()


@app.post("/pm-analysis", dependencies=[Depends(verify_token)])
def pm_analysis(request: PMAnalysisRequest):
    try:
        service = PmAnalysisService(
            dataset_path=os.path.join(dataset_dir, request.dataset),
            dataset_csv_delimiter=request.dataset_csv_delimiter,
            output_path=request.output_path
        )
        result = service.run_pm_analysis()
        
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/store-dataset", dependencies=[Depends(verify_token)])
def run_script(request: DatasetToStoreRequest):
    try:
        output_path = StoreDatasetAsCsvService.store_json_dataset_as_csv(request.filename, request.data)
        return {"success": True, "file": output_path}
    except ValueError as ve:
        raise HTTPException(status_code=400, detail=str(ve))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post(
    "/simplify-dfg",
    summary="Simplify a Directly-Follows Graph (DFG) using an LLM",
    description=(
        "Simplifies a Directly-Follows Graph (DFG) using a Large Language Model (LLM). "
        "This endpoint requires a **previous process mining analysis** that has generated a DFG file in PM4Py format.\n\n"
        "**Required input:**\n"
        "- `output_path` (str): Path where the DFG file to simplify is located.\n"
        "\n**Optional input:**\n"
        "- `deterministic_ratio` (Optional[float], range `(0, 100]`): when provided, applies a deterministic "
        "frequency pre-filter to the DFG before LLM simplification, retaining the top `deterministic_ratio`% "
        "most frequent transitions. Transitions in the same frequency tier at the cutoff are all kept or all "
        "discarded (no arbitrary tie-breaking). When omitted, the LLM simplification runs on the original DFG.\n"
        "**Example input:**\n"
        "```json\n"
        "{\n"
        "  \"output_path\": \"my-folder\",\n"
        "  \"deterministic_ratio\": 20\n"
        "}\n"
        "```"
        "\n\n"
        "**Returns:**\n"
        "- `message`: Confirmation of successful simplification.\n"
        "- `output_analysis`: Path to the analysis file generated by the LLM.\n"
        "- `llm_simplified_dfg`: Path to the simplified DFG file generated by the LLM.\n"
        "- `simplified_dfg`: Path to the simplified DFG file in PM4Py format.\n"
        "- `simplified_dfg_images`: Paths to the images representing the simplified DFG, keyed by format.\n\n"
        "**Example response:**\n"
        "```json\n"
        "{\n"
        "  \"message\": \"DFG simplified successfully\",\n"
        "  \"output_analysis\": \"/output/simplified-dfg-analysis.txt\",\n"
        "  \"llm_simplified_dfg\": \"/output/llm-simplified-dfg.txt\",\n"
        "  \"simplified_dfg\": \"/output/simplified-dfg.dfg\",\n"
        "  \"simplified_dfg_images\": {\"svg\": \"/output/simplified-dfg.svg\", \"png\": \"/output/simplified-dfg.png\"}\n"
        "}\n"
        "```"
    ),
    dependencies=[Depends(verify_token)]
)
def simplify_dfg_endpoint(request: SimplifyDFGRequest):
    try:
        
        result = SimplifyDFGService.simplify_dfg(
            output_path=request.output_path,
            deterministic_ratio=request.deterministic_ratio
        )

        return {
            "message": "DFG simplified successfully",
            "output_analysis": result["output_analysis"],
            "llm_simplified_dfg": result["llm_simplified_dfg"],
            "simplified_dfg": result["simplified_dfg"],
            "simplified_dfg_images": result["simplified_dfg_images"]
        }

    except ValueError as ve:
        raise HTTPException(status_code=400, detail=str(ve))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post(
    "/summarize-simplified-dfg",
    summary="Generate a short explanatory summary of a simplified DFG using an LLM",
    description=(
        "Generates a short, concise explanatory summary (TL;DR) of a simplified "
        "Directly-Follows Graph (DFG) using a Large Language Model (LLM). "
        "This endpoint requires a **previous `/simplify-dfg` run** that has generated "
        "the simplified DFG inside the given analysis directory.\n\n"
        "**Required input:**\n"
        "- `analysis_dir` (str): Directory where the simplified DFG is located.\n"
        "**Example input:**\n"
        "```json\n"
        "{\n"
        "  \"analysis_dir\": \"my-folder\"\n"
        "}\n"
        "```"
        "\n\n"
        "**Returns:**\n"
        "- `message`: Confirmation of successful summary generation.\n"
        "- `summary_file`: Path to the summary file generated by the LLM.\n"
        "- `summary`: The generated summary text.\n\n"
        "**Example response:**\n"
        "```json\n"
        "{\n"
        "  \"message\": \"Simplified DFG summarized successfully\",\n"
        "  \"summary_file\": \"/output/my-folder/simplified-dfg-summary.txt\",\n"
        "  \"summary\": \"## Summary ...\"\n"
        "}\n"
        "```"
    ),
    dependencies=[Depends(verify_token)]
)
def summarize_simplified_dfg_endpoint(request: SummarizeSimplifiedDFGRequest):
    try:
        result = SummarizeSimplifiedDFGService.summarize(
            analysis_dir=request.analysis_dir
        )

        return {
            "message": "Simplified DFG summarized successfully",
            "summary_file": result["summary_file"],
            "summary": result["summary"]
        }

    except ValueError as ve:
        raise HTTPException(status_code=404, detail=str(ve))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post(
        "/create-mind-map",
        summary="Create a Mermaid mind map",
        description=(
            "Creates a Mermaid mind map based on the simplified analysis results.\n\n"
            "The format of the image is set in configuration (default is svg).\n\n"
            "**Expected input:**\n"
            "- `analysis_dir` (str): Directory where the analysis results are stored."
            "This directory should contain the simplified DFG analysis file.\n\n"
            "**Example response:**\n"
            "```json\n"
            "{\n"
            "  \"mind_map_file\": \"output/mind_map.mmd\",\n"
            "  \"mind_map_image_file\": \"output/mind_map.svg\"\n"
            "}\n"
            "```"
        ),
        dependencies=[Depends(verify_token)]
)
def create_mind_map(request: CreateMindMapRequest):

    logger.info("Received request to create mind map")

    basepath = os.path.join(output_dir, request.analysis_dir)

    if not os.path.isdir(basepath):
        raise HTTPException(status_code=404, detail="Analysis directory not found")
    
    mind_map_builder_service = MindMapBuilderService()
    result = mind_map_builder_service.build_mind_map(basepath)

    logger.info("Mind map created successfully.")
    logger.debug(f"Mind map file: {result['mind_map_file']}")
    logger.debug(f"Mind map image file: {result['mind_map_image_file']}")


    return result


@app.get(
        "/get-analysis-files",
        summary="Get analysis result file paths",
        description=(
            "Retrieves the file paths of the analysis results for a given output directory.\n\n"
            "**Example response:**\n"
            "```json\n"
            "{\n"
            "  \"dfg_analysis\": \"/output/my-folder/dfg-analysis.txt\",\n"
            "  \"dfg_images\": {\"svg\": \"/output/my-folder/dfg.svg\"},\n"
            "  \"simplified_dfg_analysis\": \"/output/my-folder/simplified-dfg-analysis.txt\",\n"
            "  \"simplified_dfg_summary\": \"/output/my-folder/simplified-dfg-summary.txt\",\n"
            "  \"simplified_dfg_images\": {\"svg\": \"/output/my-folder/simplified-dfg.svg\"}\n"
            "}\n"
            "```"
        ),
        dependencies=[Depends(verify_token)]
)
def get_analysis_files(analysis_dir: str = Query(
                                    alias="analysis_dir",
                                    description="Directory where the analysis results are stored"
                                    )
    ):

    basepath = os.path.join(output_dir, analysis_dir)

    if not os.path.isdir(basepath):
        raise HTTPException(status_code=404, detail="Analysis directory not found")

    files = GetAnalysisService().get_analysis_files(basepath)

    result = {}

    if os.path.isfile(files["dfg_analysis"]):
        result["dfg_analysis"] = files["dfg_analysis"]
    else:
        result["dfg_analysis"] = "No analysis file found for DFG."

    if os.path.isfile(files["simplified_dfg_analysis"]):
        result["simplified_dfg_analysis"] = files["simplified_dfg_analysis"]
    else:
        result["simplified_dfg_analysis"] = "No analysis file found for simplified DFG."

    if os.path.isfile(files["simplified_dfg_summary"]):
        result["simplified_dfg_summary"] = files["simplified_dfg_summary"]
    else:
        result["simplified_dfg_summary"] = "No summary file found for simplified DFG."

    dfg_images = {fmt: path for fmt, path in files["dfg_images"].items() if os.path.isfile(path)}
    if dfg_images:
        result["dfg_images"] = dfg_images

    simplified_dfg_images = {
        fmt: path for fmt, path in files["simplified_dfg_images"].items() if os.path.isfile(path)
    }
    if simplified_dfg_images:
        result["simplified_dfg_images"] = simplified_dfg_images

    return result

    

