from fastapi import FastAPI, HTTPException, Query, status, Depends
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from dotenv import load_dotenv
from lib.dtos import *
from config.constants import *
from lib.store_dataset_as_csv import store_json_dataset_as_csv
from lib.DFGSimplifier import DFGSimplifier
import subprocess
import os
import logging
import sys

load_dotenv()
API_TOKEN = os.getenv("API_TOKEN")
LOG_LEVEL = os.getenv("LOG_LEVEL", "DEBUG").upper()

logging.basicConfig(
    level=getattr(logging, LOG_LEVEL, logging.INFO),
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)]
)

logger = logging.getLogger(__name__)


security = HTTPBearer()


def verify_token(credentials: HTTPAuthorizationCredentials = Depends(security)):
    if credentials.credentials != API_TOKEN:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or missing token" + API_TOKEN,
        )

app = FastAPI()

@app.post("/run", dependencies=[Depends(verify_token)])
def run_script(request: PMAnalysisRequest):
    script_path = os.path.join("/app", request.script)
    if not os.path.isfile(script_path):
        return {"error": f"Script not found: {script_path}"}

    try:
        # Run the script as a subprocess and capture the output
        result = subprocess.run(
            [
                "python3",
                script_path,
                "--dataset-path", request.datasetPath,
                "--dataset-csv_delimiter", request.datasetCsvDelimiter,
                "--output_path", request.outputPath
            ],
            capture_output=True,
            text=True,
            timeout=1800 # Timeout after 30 minutes
        )
        return {
            "stdout": result.stdout,
            "stderr": result.stderr,
            "returncode": result.returncode
        }
    except Exception as e:
        return {"error": str(e)}


@app.post("/store-dataset", dependencies=[Depends(verify_token)])
def run_script(request: DatasetToStoreRequest):
    try:
        output_path = store_json_dataset_as_csv(request.filename, request.data)
        return {"success": True, "file": output_path}
    except ValueError as ve:
        raise HTTPException(status_code=400, detail=str(ve))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post(
    "/simplify-dfg",
    summary="Simplify a Directly-Follows Graph (DFG) using an LLM",
    description=(
        "Simplifies a Directly-Follows Graph (DFG) using a Large Language Model (LLM). "
        "This endpoint requires a **previous process mining analysis** that has generated a DFG file in PM4Py format.\n\n"
        "**Required input:**\n"
        "- `dfg_file` (str): Full path to the DFG file to simplify.\n"
        "\n**Optional input:**\n"
        "- `prompt_context` (Optional[List[str]]): list of prompt context lines to replace the default context. Useful for customizing the LLM behavior.\n\n"
        "**Example input:**\n"
        "```json\n"
        "{\n"
        "  \"dfg_file\": \"output/my-folder/dfg.dfg\",\n"
        "  \"prompt_context\": [\n"
        "    \"### CONTEXT ###\\n\",\n"
        "    \"You are an expert in process mining and data analysis, with a focus on educational data.\",\n"
        "    \"The section ### DFG MODEL ### contains a Directly-Follows Graph (DFG) model in PM4Py format, extracted from Moodle logs.\",\n"
        "    \"This model represents the activity behavior of students.\",\n"
        "    \"The structure and format of the DFG are described in the section ### DFG FORMAT ### above.\"\n"
        "  ]\n"
        "}\n"
        "```"
        "\n\n"
        "**Returns:**\n"
        "- `message`: Confirmation of successful simplification.\n"
        "- `output_analysis`: Path to the analysis file generated by the LLM.\n"
        "- `simplified_dfg`: Path to the simplified DFG file.\n"
        "- `simplified_dfg_image`: Path to the image representing the simplified DFG.\n\n"
        "**Example response:**\n"
        "```json\n"
        "{\n"
        "  \"message\": \"DFG simplified successfully\",\n"
        "  \"output_analysis\": \"output/simplified-dfg-analysis.txt\",\n"
        "  \"simplified_dfg\": \"output/simplified-dfg.dfg\",\n"
        "  \"simplified_dfg_image\": \"output/simplified-dfg.png\"\n"
        "}\n"
        "```"
    ),
    dependencies=[Depends(verify_token)]
)
def simplify_dfg_endpoint(request: SimplifyDFGRequest):
    try:
        simplifier = DFGSimplifier()
        
        if not os.path.exists(request.dfg_file):
            raise HTTPException(status_code=404, detail="DFG file not found.")
        
        if request.prompt_context is not None:
            simplifier.set_context_prompt(request.prompt_context)
            logger.debug(f"Context prompt updated: {simplifier.get_context_prompt()}")
        
        input_dir = os.path.dirname(request.dfg_file)

        llm_simplified_dfg_file = os.path.join(input_dir, "llm-simplified-dfg.dfg")
        simplifier.simplify_dfg(request.dfg_file, llm_simplified_dfg_file)

        simplified_dfg_file = os.path.join(input_dir, "simplified-dfg.dfg")
        simplifier.clean_dfg(request.dfg_file, llm_simplified_dfg_file, simplified_dfg_file)

        output_analysis = os.path.join(input_dir, "simplified-dfg-analysis.txt")
        simplifier.analyze_simplified_dfg(simplified_dfg_file, output_analysis)

        simplified_dfg_image = os.path.join(input_dir, "simplified-dfg.png")
        simplifier.convert_dfg_to_image(simplified_dfg_file, simplified_dfg_image)

        return {
            "message": "DFG simplified successfully",
            "output_analysis": output_analysis,
            "simplified_dfg": simplified_dfg_file,
            "simplified_dfg_image": simplified_dfg_image
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get(
        "/get-analysis",
        summary="Get analysis results",
        description=("Retrieves the analysis results for a given output directory."),
        dependencies=[Depends(verify_token)]
)
def get_analysis(analysis_dir: str = Query(
                                    alias="analysis_dir",
                                    description="Directory where the analysis results are stored"
                                    )
    ):

    basepath = os.path.join(OUTPUT_PATH, analysis_dir)

    if not os.path.isdir(basepath):
        raise HTTPException(status_code=404, detail="Analysis directory not found")
    
    dfgBasepath = os.path.join(basepath, "dfg.png")
    dfgAnalysisBasepath = os.path.join(basepath, "dfg-analysis.txt")
    simplifiedDfgBasepath = os.path.join(basepath, "simplified-dfg.png")
    simplifiedDfgAnalysisBasepath = os.path.join(basepath, "simplified-dfg-analysis.txt")
    
    if not os.path.isfile(dfgBasepath) or not os.path.isfile(dfgAnalysisBasepath):
        raise HTTPException(status_code=404, detail=dfgBasepath + " or " + dfgAnalysisBasepath + " not found")

    try:
        with open(dfgAnalysisBasepath, "r") as f:
            dfgAnalysisText = f.read()
        with open(dfgBasepath, "rb") as f:
            dfgImageBytes = f.read()

        result = {
            "analysis": dfgAnalysisText,
            "dfg_image": dfgImageBytes.hex()
        }

        if os.path.isfile(simplifiedDfgAnalysisBasepath):
            with open(simplifiedDfgAnalysisBasepath, "r") as f:
                simplifiedDfgAnalysisText = f.read()
            result["simplified_dfg_analysis"] = simplifiedDfgAnalysisText

        if os.path.isfile(simplifiedDfgBasepath):
            with open(simplifiedDfgBasepath, "rb") as f:
                simplifiedDfgImageBytes = f.read()
            result["simplified_dfg_image"] = simplifiedDfgImageBytes.hex()

        return result

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))