from fastapi import FastAPI, HTTPException, Query, status, Depends
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from dotenv import load_dotenv
from source.run_pm_analysis import run_pm_analysis
from source.dtos import *
from config.constants import *
from source.store_dataset_as_csv import store_json_dataset_as_csv
from source.DFGSimplifier import DFGSimplifier
from source.DFGTransformer import DFGTransformer
from source.Filename import Filename
import os
import logging
import sys



load_dotenv()
API_TOKEN = os.getenv("API_TOKEN")
LOG_LEVEL = os.getenv("LOG_LEVEL", "DEBUG").upper()

if not API_TOKEN:
    raise RuntimeError("API_TOKEN is not set in environment variables")

logging.basicConfig(
    level=getattr(logging, LOG_LEVEL, logging.INFO),
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)]
)

logger = logging.getLogger(__name__)


security = HTTPBearer()


fn = Filename()


def verify_token(credentials: HTTPAuthorizationCredentials = Depends(security)):
    token = credentials.credentials
    if not token or token != API_TOKEN:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or missing token" + API_TOKEN,
        )

app = FastAPI()


@app.post("/pm-analysis", dependencies=[Depends(verify_token)])
def pm_analysis(request: PMAnalysisRequest):
    try:
        result = run_pm_analysis(
            dataset_path=request.datasetPath,
            dataset_csv_delimiter=request.datasetCsvDelimiter,
            output_path=request.outputPath
        )
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/store-dataset", dependencies=[Depends(verify_token)])
def run_script(request: DatasetToStoreRequest):
    try:
        output_path = store_json_dataset_as_csv(request.filename, request.data)
        return {"success": True, "file": output_path}
    except ValueError as ve:
        raise HTTPException(status_code=400, detail=str(ve))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post(
    "/simplify-dfg",
    summary="Simplify a Directly-Follows Graph (DFG) using an LLM",
    description=(
        "Simplifies a Directly-Follows Graph (DFG) using a Large Language Model (LLM). "
        "This endpoint requires a **previous process mining analysis** that has generated a DFG file in PM4Py format.\n\n"
        "**Required input:**\n"
        "- `outputPath` (str): Path where the DFG file to simplify is located.\n"
        "\n**Optional input:**\n"
        "- `prompt_context` (Optional[List[str]]): list of prompt context lines to replace the default context. Useful for customizing the LLM behavior.\n\n"
        "**Example input:**\n"
        "```json\n"
        "{\n"
        "  \"outputPath\": \"my-folder\",\n"
        "  \"prompt_context\": [\n"
        "    \"### CONTEXT ###\\n\",\n"
        "    \"You are an expert in process mining and data analysis, with a focus on educational data.\",\n"
        "    \"The section ### DFG MODEL ### contains a Directly-Follows Graph (DFG) model extracted from Moodle logs.\",\n"
        "    \"This model represents the activity behavior of students.\",\n"
        "    \"The structure and format of the DFG are described in the section ### DFG FORMAT ### above.\"\n"
        "  ]\n"
        "}\n"
        "```"
        "\n\n"
        "**Returns:**\n"
        "- `message`: Confirmation of successful simplification.\n"
        "- `output_analysis`: Path to the analysis file generated by the LLM.\n"
        "- `llm_simplified_dfg`: Path to the simplified DFG file generated by the LLM.\n"
        "- `simplified_dfg`: Path to the simplified DFG file in PM4Py format.\n"
        "- `simplified_dfg_image`: Path to the image representing the simplified DFG.\n\n"
        "**Example response:**\n"
        "```json\n"
        "{\n"
        "  \"message\": \"DFG simplified successfully\",\n"
        "  \"output_analysis\": \"output/simplified-dfg-analysis.txt\",\n"
        "  \"llm_simplified_dfg\": \"output/llm-simplified-dfg.txt\",\n"
        "  \"simplified_dfg\": \"output/simplified-dfg.dfg\",\n"
        "  \"simplified_dfg_image\": \"output/simplified-dfg.png\"\n"
        "}\n"
        "```"
    ),
    dependencies=[Depends(verify_token)]
)
def simplify_dfg_endpoint(request: SimplifyDFGRequest):
    try:
        simplifier = DFGSimplifier()
        transformer = DFGTransformer()
        
        input_dir = os.path.join(OUTPUT_PATH, request.outputPath)
        dfg_file = os.path.join(input_dir, fn.get_filename("dfg.json"))

        if not os.path.exists(dfg_file):
            raise HTTPException(status_code=404, detail="DFG file not found.")
        
        if request.prompt_context is not None:
            simplifier.set_context_prompt(request.prompt_context)
            logger.debug(f"Context prompt updated: {simplifier.get_context_prompt()}")


        print("Transforming DFG JSON to use generic activity names...")
        json_dfg_file = fn.get_filename_path("dfg.json", input_dir)
        json_dfg_generics_file = fn.get_filename_path("dfg.json_generic_act", input_dir)
        json_activity_mapping_file = fn.get_filename_path("dfg.json_activity_mapping_from_dfg", input_dir)

        transformer.dfg_json_replace_activities_with_generics(
            input_json_path=json_dfg_file,
            output_json_path=json_dfg_generics_file,
            mapping_output_path=json_activity_mapping_file
        )

        print(f"Simplifying DFG in json ({json_dfg_generics_file}) using LLM...")
        llm_simplified_dfg_file = fn.get_filename_path("dfg.json_llm_simplified", input_dir)
        simplifier.simplify_dfg(json_dfg_generics_file, llm_simplified_dfg_file)
        
        print("Restoring simplified DFG in json to use original activity names...")
        llm_restored_simplified_dfg_file = fn.get_filename_path("dfg.json_llm_restored_simplified", input_dir)

        transformer.dfg_json_restore_activity_names(
            act_json_path=llm_simplified_dfg_file,
            mapping_path=json_activity_mapping_file,
            output_json_path=llm_restored_simplified_dfg_file
        )

        print("Restoring simplified DFG in json to pm4py DFG format...")
        simplified_dfg_file = fn.get_filename_path("dfg.simplified", input_dir)
        transformer.dfg_named_json_to_pm4py(
            named_json_path=llm_restored_simplified_dfg_file,
            dfg_output_path=simplified_dfg_file
        )

        output_analysis = fn.get_filename_path("dfg.simplified_analysis", input_dir)
        simplifier.analyze_simplified_dfg(llm_restored_simplified_dfg_file, output_analysis)

        simplified_dfg_image = fn.get_filename_path("dfg.simplified_image", input_dir)
        simplifier.convert_dfg_to_image(simplified_dfg_file, simplified_dfg_image)

        simplifier.compute_simplification_info(
            original_dfg_path=os.path.join(input_dir, fn.get_filename("dfg.raw")),
            simplified_dfg_path=simplified_dfg_file
        )

        return {
            "message": "DFG simplified successfully",
            "output_analysis": output_analysis,
            "llm_simplified_dfg": llm_restored_simplified_dfg_file,
            "simplified_dfg": simplified_dfg_file,
            "simplified_dfg_image": simplified_dfg_image
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get(
        "/get-analysis",
        summary="Get analysis results",
        description=(
            "Retrieves the analysis results for a given output directory. Includes simplified DFG information if exists.\n\n"
            "**Example response:**\n"
            "```json\n"
            "{\n"
            "  \"analysis\": \"XXX\",\n"
            "  \"dfg_image\": \"XXX\",\n"
            "  \"simplified_dfg_analysis\": \"XXX\",\n"
            "  \"simplified_dfg_image\": \"XXX\"\n"
            "}\n"
            "```"
        ),
        dependencies=[Depends(verify_token)]
)
def get_analysis(analysis_dir: str = Query(
                                    alias="analysis_dir",
                                    description="Directory where the analysis results are stored"
                                    )
    ):

    basepath = os.path.join(OUTPUT_PATH, analysis_dir)

    if not os.path.isdir(basepath):
        raise HTTPException(status_code=404, detail="Analysis directory not found")
    
    dfgBasepath = os.path.join(basepath, "dfg.png")
    dfgAnalysisBasepath = os.path.join(basepath, "dfg-analysis.txt")
    simplifiedDfgBasepath = os.path.join(basepath, "simplified-dfg.png")
    simplifiedDfgAnalysisBasepath = os.path.join(basepath, "simplified-dfg-analysis.txt")
    
    if not os.path.isfile(dfgBasepath) or not os.path.isfile(dfgAnalysisBasepath):
        raise HTTPException(status_code=404, detail=dfgBasepath + " or " + dfgAnalysisBasepath + " not found")

    try:
        with open(dfgAnalysisBasepath, "r") as f:
            dfgAnalysisText = f.read()
        with open(dfgBasepath, "rb") as f:
            dfgImageBytes = f.read()

        result = {
            "analysis": dfgAnalysisText,
            "dfg_image": dfgImageBytes.hex()
        }

        if os.path.isfile(simplifiedDfgAnalysisBasepath):
            with open(simplifiedDfgAnalysisBasepath, "r") as f:
                simplifiedDfgAnalysisText = f.read()
            result["simplified_dfg_analysis"] = simplifiedDfgAnalysisText

        if os.path.isfile(simplifiedDfgBasepath):
            with open(simplifiedDfgBasepath, "rb") as f:
                simplifiedDfgImageBytes = f.read()
            result["simplified_dfg_image"] = simplifiedDfgImageBytes.hex()

        return result

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))